# Site settings
title:          "DTSheffler.com"
author:         "D.T. Sheffler"
email:          ""
description:    "The personal website of D.T. Sheffler"
baseurl:        "https://www.dtsheffler.com"
url:            "https://www.dtsheffler.com"
future:         false
excerpt_separator: <!--more-->

plugins:
  - jekyll-gist
  - jekyll-pandoc-multiple-formats

# lunr_search:
#   excludes: [sitemap.xml,index.html,search,archive,papers,share,teaching]

# Build settings
markdown:       Pandoc
pandoc:
    skip:
      full: false
      posts: false
      categories: false
    imposition: false
    binder: false
    flags: '-f markdown+smart --citeproc --bibliography=C:\\Users\\daniel.sheffler\\OneDrive\\Jabref\\mybib.bib --csl=C:\\Users\\daniel.sheffler\\OneDrive\\Pandoc\\default.csl'
    site-flags: '-f markdown+smart --citeproc --bibliography=C:\\Users\\daniel.sheffler\\OneDrive\\Jabref\\mybib.bib --csl=C:\\Users\\daniel.sheffler\\OneDrive\\Pandoc\\default.csl'
markdown_ext:   markdown,mkdown,mkdn,mkd,md
permalink:      /notebook/:year-:month-:day-:title/
encoding:       utf-8

incremental: true

collections:
  featuredessays:
    output: true
    order:
      - The-Unread-Library.md
      - Gravitas-Dignitas-Pietas.md
      - Growing-Up-In-Church.md
  essays:
    output: true
  share:
    output: true
  teaching:
    output: true
  presentations:
    output: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts" # overrides previous default layout
  -
    scope:
      path: ""
      type: "presentations"
    values:
      layout: "presentation"
